name: denbigh_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.3+6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_storage: ^12.4.9
  cloud_firestore: ^5.6.11
  feather_icons: ^1.2.0
  font_awesome_flutter: ^10.8.0
  stylish_bottom_bar: ^1.1.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.7
  flutter_credit_card: ^4.1.0
  intl: ^0.20.2
  provider: ^6.1.5
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  async: ^2.13.0
  rxdart: ^0.28.0
  flutter_paypal_payment: ^1.0.8
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/png1.png
    - assets/png2.png
    - assets/png3.png
    - assets/fonts/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Switzer
      fonts:
        - asset: assets/fonts/Switzer-Medium.otf
          weight: 500
        - asset: assets/fonts/Switzer-Bold.otf
          weight: 700
        - asset: assets/fonts/Switzer-Regular.otf
          weight: 400
        - asset: assets/fonts/Switzer-italic.otf
          style: italic
    - family: OleoScript
      fonts:
        - asset: assets/fonts/OleoScript-Bold.ttf
          weight: 700
        - asset: assets/fonts/OleoScript-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
