// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0XCjPfKedSSLaRfQUYWKoap2N3P80G6U',
    appId: '1:300840934452:web:a3d8564c81770a14eefe61',
    messagingSenderId: '300840934452',
    projectId: 'farmers-app-fbdb3',
    authDomain: 'farmers-app-fbdb3.firebaseapp.com',
    storageBucket: 'farmers-app-fbdb3.firebasestorage.app',
    measurementId: 'G-MM6N13QD8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgAej9FXPUUcXkmfzJlYJFGmGvb1E1ICY',
    appId: '1:300840934452:android:6c2a478d04d68e8aeefe61',
    messagingSenderId: '300840934452',
    projectId: 'farmers-app-fbdb3',
    storageBucket: 'farmers-app-fbdb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC31LqWfPqpXFrFGMgPsIm8eXPLx6igg_Y',
    appId: '1:300840934452:ios:ef1699f517190b80eefe61',
    messagingSenderId: '300840934452',
    projectId: 'farmers-app-fbdb3',
    storageBucket: 'farmers-app-fbdb3.firebasestorage.app',
    iosBundleId: 'com.example.denbighApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC31LqWfPqpXFrFGMgPsIm8eXPLx6igg_Y',
    appId: '1:300840934452:ios:ef1699f517190b80eefe61',
    messagingSenderId: '300840934452',
    projectId: 'farmers-app-fbdb3',
    storageBucket: 'farmers-app-fbdb3.firebasestorage.app',
    iosBundleId: 'com.example.denbighApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0XCjPfKedSSLaRfQUYWKoap2N3P80G6U',
    appId: '1:300840934452:web:8fa531333dc930f4eefe61',
    messagingSenderId: '300840934452',
    projectId: 'farmers-app-fbdb3',
    authDomain: 'farmers-app-fbdb3.firebaseapp.com',
    storageBucket: 'farmers-app-fbdb3.firebasestorage.app',
    measurementId: 'G-S26GEGPG71',
  );
}
