

import 'package:flutter/material.dart';

final List<String> categories = [
  'Vegetables',
  'Fruits',
  'Dairy',
  'Grains',
  'Meat',
  'Poultry',
  'Seafood',
];

final List<String> units = [
  'kg',
  'dozen',
  'box',
  'bag',
  'carton',
  'pack',
  'LBS',
  'ounce',
];

final Map<String, Color> categoryColors = {
  'Vegetables': Colors.green.shade100,
  'Fruits': Colors.orange.shade100,
  'Dairy': Colors.blue.shade100,
  'Grains': Colors.brown.shade100,
  'Meat': Colors.red.shade100,
  'Bakery': Colors.amber.shade100,
  'Beverages': Colors.cyan.shade100,
  'Seafood': Colors.teal.shade100,
};

final Map<String, Color> statuses = {
  'Processing': Colors.yellow,
  'Confirmed': Colors.green,
  'Shipped': Colors.blue,
  'Completed': Colors.grey,
  'Cancelled': Colors.red,
};

final List<String> farmProductNames = [
  'Tomatoes',
  'Cucumbers',
  'Lettuce',
  'Carrots',
  'Potatoes',
  'Onions',
  'Bell Peppers',
  'Eggplants',
  'Zucchini',
  'Pumpkins',
  'Spinach',
  'Broccoli',
  'Cauliflower',
  'Cabbage',
  'Kale',
  'Radishes',
  'Beets',
  'Garlic',
  'Ginger',
  'Basil',
  'Parsley',
  'Mint',
  'Rosemary',
  'Thyme',
  'Oregano',
  'Chives',
  'Corn',
  'Peas',
  'Green Beans',
  'Asparagus',
  'Sweet Potatoes',
  'Mushrooms',
  'Watermelon',
  'Cantaloupe',
  'Strawberries',
  'Blueberries',
  'Raspberries',
  'Blackberries',
  'Apples',
  'Pears',
  'Peaches',
  'Plums',
  'Cherries',
  'Grapes',
  'Oranges',
  'Lemons',
  'Limes',
  'Bananas',
  'Pineapple',
  'Mango',
  'Papaya',
  'Avocado',
  'Beef',
  'Chicken',
  'Turkey',
  'Pork',
  'Lamb',
  'Goat',
  'Duck',
  'Rabbit',
  'Fish',
  'Shrimp',
  'Crab',
  'Lobster',
  'Milk',
  'Cheese',
  'Yogurt',
  'Butter',
  'Eggs',
  'Honey',
  'Wheat',
  'Barley',
  'Oats',
  'Rice',
  'Cornmeal',
  'Flour',
  'Almonds',
  'Walnuts',
  'Pecans',
  'Cashews',
  'Peanuts',
  'Sunflower Seeds',
  'Pumpkin Seeds',
  'Olive Oil',
  'Coconut',

];
