import 'package:flutter/material.dart';

final List<String> categories = [
  'All',
  'Vegetables',
  'Fruits',
  'Dairy',
  'Grains',
  'Meat',
  'Poultry',
  'Seafood',
  'Farm Equipment',
  'Seeds',
  'Fertilizers',
  'Pesticides',
  'Tools',
  'Irrigation Equipment',
  'Harvesting Tools',
  'Uncategorized', // Fallback for empty categories
];

final List<String> units = [
  'kg',
  'dozen',
  'box',
  'bag',
  'carton',
  'pack',
  'LBS',
  'ounce',
  'unit',
  'Flat',
];

// Tool/Equipment specific categories
final List<String> toolCategories = [
  'Farm Equipment',
  'Seeds',
  'Fertilizers',
  'Pesticides',
  'Tools',
  'Irrigation Equipment',
  'Harvesting Tools',
  'Other',
];

// Tool/Equipment specific units
final List<String> toolUnits = [
  'piece',
  'hour',
  'day',
  'week',
  'month',
  'kg',
  'litre',
  'bag',
  'box',
  'set',
];

final Map<String, Color> categoryColors = {
  'All': Colors.grey.shade300,
  'Vegetables': Colors.green.shade100,
  'Fruits': Colors.orange.shade100,
  'Dairy': Colors.blue.shade100,
  'Grains': Colors.brown.shade100,
  'Meat': Colors.red.shade100,
  'Poultry': Colors.yellow.shade100,
  'Bakery': Colors.amber.shade100,
  'Beverages': Colors.cyan.shade100,
  'Seafood': Colors.teal.shade100,
  'Farm Equipment': Colors.indigo.shade100,
  'Seeds': Colors.lightGreen.shade100,
  'Fertilizers': Colors.deepOrange.shade100,
  'Pesticides': Colors.purple.shade100,
  'Tools': Colors.blueGrey.shade100,
  'Irrigation Equipment': Colors.lightBlue.shade100,
  'Harvesting Tools': Colors.deepPurple.shade100,
  'Uncategorized':
      Colors.grey.shade200, // Fallback color for uncategorized items
};

final Map<String, Color> statuses = {
  'Processing': Colors.yellow,
  'Confirmed': Colors.green,
  'Preparing': Colors.orange,
  'Shipped': Colors.blue,
  'Completed': Colors.grey,
  'Cancelled': Colors.red,
};

final List<String> farmProductNames = [
  'Tomatoes',
  'Cucumbers',
  'Lettuce',
  'Carrots',
  'Potatoes',
  'Onions',
  'Bell Peppers',
  'Eggplants',
  'Zucchini',
  'Pumpkins',
  'Spinach',
  'Broccoli',
  'Cauliflower',
  'Cabbage',
  'Kale',
  'Radishes',
  'Beets',
  'Garlic',
  'Ginger',
  'Basil',
  'Parsley',
  'Mint',
  'Rosemary',
  'Thyme',
  'Oregano',
  'Chives',
  'Corn',
  'Peas',
  'Green Beans',
  'Asparagus',
  'Sweet Potatoes',
  'Mushrooms',
  'Watermelon',
  'Cantaloupe',
  'Strawberries',
  'Blueberries',
  'Raspberries',
  'Blackberries',
  'Apples',
  'Pears',
  'Peaches',
  'Plums',
  'Cherries',
  'Grapes',
  'Oranges',
  'Lemons',
  'Limes',
  'Bananas',
  'Pineapple',
  'Mango',
  'Papaya',
  'Avocado',
  'Beef',
  'Chicken',
  'Turkey',
  'Pork',
  'Lamb',
  'Goat',
  'Duck',
  'Rabbit',
  'Fish',
  'Shrimp',
  'Crab',
  'Lobster',
  'Milk',
  'Cheese',
  'Yogurt',
  'Butter',
  'Eggs',
  'Honey',
  'Wheat',
  'Barley',
  'Oats',
  'Rice',
  'Cornmeal',
  'Flour',
  'Almonds',
  'Walnuts',
  'Pecans',
  'Cashews',
  'Peanuts',
  'Sunflower Seeds',
  'Pumpkin Seeds',
  'Olive Oil',
  'Coconut',
];
