List<String> jamaicaParishesWithTowns = [
  'Kingston - Kingston',
  'St. Andrew - Kingston',
  'St. Andrew - New Kingston',
  'St. Andrew - Half Way Tree',
  'St. Thomas - St. Thomas Parish Capital',
  'St. Thomas - Morant Bay',
  'Portland -  Buff Bay',
  'Portland - Port Antonio',
  'St. Mary - Kingston',
  'St. Mary - Oracabessa',
  'St. Mary - Boscobel',
  'St. Ann - Ocho Rios',
  'St. Ann - St. Ann’s Bay',
  'St. Ann - Runaway Bay',
  'Trelawny - Falmouth',
  'Trelawny - Trelawny Parish Capital',
  'Trelawny - Martha Brae',
  'St. James - Montego Bay',
  'St. James - St. James Parish Capital',
  'Hanover - Hanover',
  'Hanover - Lucea',
  'Westmoreland - Savanna-la-Mar',
  'Westmoreland - Little London',
  'St. Elizabeth - Santa Cruz',
  'St. Elizabeth - Black River',
  'St. Elizabeth - Junction',
  'Manchester - Mandeville',
  'Manchester - Christiana',
  'Clarendon - Lionel Town',
  'Clarendon - May Pen',
  'St. Catherine - Spanish Town',
  'St. Catherine - Portmore',
  'St. Catherine - Portmore',
];